# Generated by Django 5.1.4 on 2025-02-02 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_delete_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='author',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='isbn',
            new_name='series',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='price',
            new_name='year',
        ),
    ]
